[[redirects]]
from = "dashboard"
to = "/fr/dashboard/dashboard.html"
status = 200

[[redirects]]
from = "dashboarden"
to = "/en/dashboard/dashboard.html"
status = 200


[[redirects]]
from = "/detail_view"
to = "/dashboard/agriculterdisplay.html"
status = 200

[[redirects]]
from = "details_view*"
to = "/detail_view:splat"


[[redirects]]
from = "/fr"
to = "/fr/index.html"
status = 200


[[redirects]]
from = "/en"
to = "/en/index.html"
status = 200